Repository flarioncode/polars, pull requests merged in 2024-11, with the labels that each got.

#16 fix: Fix not() and or() allowed types
  .github/workflows/benchmark.yml
  .github/workflows/test-coverage.yml
  Cargo.lock
  crates/polars-core/src/chunked_array/ops/filter.rs
  crates/polars-core/src/series/implementations/binary.rs
  crates/polars-core/src/series/implementations/boolean.rs
  crates/polars-core/src/series/implementations/floats.rs
  crates/polars-core/src/series/implementations/list.rs
  crates/polars-core/src/series/implementations/mod.rs
  crates/polars-core/src/series/implementations/string.rs
  crates/polars-ops/src/series/ops/not.rs
  crates/polars-plan/src/dsl/function_expr/boolean.rs
  crates/polars-plan/src/dsl/function_expr/list.rs
  crates/polars-plan/src/plans/optimizer/simplify_expr/mod.rs
Labels: rust, python, fix

#18 feat: add flarion_aggregate function, for usage with an aggregate buffer
  crates/polars-plan/src/dsl/mod.rs
Labels: title needs formatting

#19 fix: Better support for lambda expressions related to filter
  crates/polars-core/src/chunked_array/ops/filter.rs
  crates/polars-core/src/chunked_array/ops/lambda.rs
  crates/polars-ops/src/chunked_array/list/namespace.rs
Labels: rust, python, fix

#23 fix(rust): If `profile` fail due to timeout it should not fail the collect result as well
  crates/polars-error/src/lib.rs
  crates/polars-lazy/src/frame/mod.rs
  crates/polars-lazy/src/tests/queries.rs
Labels: rust, fix

#24 feat: Implement BatchedReader and BatchedWriter for both IpcFile and IpcStream
  crates/polars-arrow/src/io/ipc/append/mod.rs
  crates/polars-arrow/src/io/ipc/write/common_sync.rs
  crates/polars-arrow/src/io/ipc/write/stream.rs
  crates/polars-arrow/src/io/ipc/write/writer.rs
  crates/polars-io/src/ipc/ipc_file.rs
  crates/polars-io/src/ipc/ipc_stream.rs
  crates/polars-io/src/ipc/mod.rs
  crates/polars-io/src/ipc/write.rs
  crates/polars-pipe/src/executors/sinks/output/ipc.rs
  crates/polars-plan/src/plans/ir/scan_sources.rs
Labels: enhancement, rust, python

#22 feat: Add support in polars for null checking in concat_str()
  crates/polars-lazy/src/tests/projection_queries.rs
  crates/polars-ops/src/chunked_array/strings/concat.rs
  crates/polars-plan/src/dsl/function_expr/strings.rs
  crates/polars-plan/src/dsl/functions/concat.rs
  crates/polars-plan/src/plans/optimizer/simplify_expr/mod.rs
  crates/polars-plan/src/plans/optimizer/simplify_expr/simplify_functions.rs
  crates/polars-python/src/functions/lazy.rs
  crates/polars-python/src/lazyframe/visitor/expr_nodes.rs
  crates/polars-sql/src/functions.rs
  docs/src/rust/user-guide/expressions/folds.rs
  py-polars/polars/functions/as_datatype.py
Labels: enhancement, rust, python

#26 fix: Use stream_position() to get written bytes because other methods are inaccurate
  crates/polars-expr/src/expressions/flarion/mod.rs
  crates/polars-expr/src/expressions/flarion/normalize_nan_and_zero.rs
  crates/polars-expr/src/expressions/mod.rs
  crates/polars-io/src/ipc/ipc_file.rs
  crates/polars-io/src/ipc/ipc_stream.rs
Labels: rust, python, fix

#27 fix(rust): Fix division with scalars
  crates/polars-compute/Cargo.toml
  crates/polars-compute/src/arithmetic/float.rs
  crates/polars-core/Cargo.toml
  crates/polars/Cargo.toml
Labels: rust, fix
