Repository flarioncode/polars, pull requests merged in 2024-12, with the labels that each got.

#31 fix: Regexp replace doesn't really need groups
  .github/workflows/lint-rust.yml
  crates/polars-ops/src/chunked_array/strings/namespace.rs
  crates/polars-plan/src/dsl/function_expr/strings.rs
  crates/polars-plan/src/dsl/string.rs
Labels: rust, python, fix

#29 fix(rust): Fix module and divide + rename feature to `consistent_arithmetic`
  crates/polars-compute/Cargo.toml
  crates/polars-compute/src/arithmetic/float.rs
  crates/polars-compute/src/arithmetic/signed.rs
  crates/polars-compute/src/arithmetic/unsigned.rs
  crates/polars-core/Cargo.toml
  crates/polars/Cargo.toml
Labels: rust, fix

#30 feat: Add support for float types and string in polars to use in lambdas
  crates/polars-core/src/chunked_array/ops/lambda.rs
  crates/polars-core/src/series/implementations/floats.rs
  crates/polars-core/src/series/implementations/string.rs
Labels: enhancement, rust, python

#32 fix(rust): String fixes - only trim direct spaces and do not split \r and \n
  crates/polars-ops/src/chunked_array/strings/flarion_split.rs
  crates/polars-ops/src/chunked_array/strings/namespace.rs
Labels: title needs formatting, rust, fix

#37 fix(rust): Remove nulls from flatten
  crates/polars-core/src/series/mod.rs
Labels: rust, fix

#40 fix: String to numerics cast should allow the following suffixes: "f", "F", "d", "D", "L"
  crates/polars-arrow/src/compute/cast/binview_to.rs
Labels: rust, python, fix

#39 fix(rust): Fix unicode length & dtype issues with array of null in lambda
  crates/polars-core/src/chunked_array/from_iterator.rs
  crates/polars-core/src/chunked_array/ops/lambda.rs
  crates/polars-core/src/chunked_array/ops/transform.rs
  crates/polars-core/src/series/implementations/floats.rs
  crates/polars-core/src/series/implementations/mod.rs
  crates/polars-plan/src/dsl/function_expr/list.rs
Labels: rust, python, fix

#42 fix: Added string to boolean casting
  crates/polars-arrow/src/compute/cast/mod.rs
  crates/polars-ops/src/chunked_array/strings/namespace.rs
Labels: rust, python, fix

#44 fix: Edit check_expand_literals to expand literals when the expression is just literals or scalars
  crates/polars-mem-engine/src/executors/projection_utils.rs
Labels: rust, python, fix

#45 feat: Allow mutable access to the reader field
  crates/polars-arrow/src/io/ipc/read/stream.rs
  crates/polars-io/src/ipc/ipc_stream.rs
Labels: enhancement, rust, python

#46 feat(rust): Add support for polars_utils to be available for the floor functions
  crates/polars/src/prelude.rs
Labels: enhancement, rust

#47 fix: Strings casting to numbers so it passes fuzz testing as well
  crates/polars-arrow/src/compute/cast/binview_to.rs
Labels: rust, python, fix

#48 chore: Export all required modules
  crates/polars-core/src/prelude.rs
  crates/polars-core/src/series/mod.rs
  crates/polars/src/prelude.rs
Labels: rust, python, internal

#43 fix(rust): Add EuqalSafeNull and StringOwned support used by filter()
  crates/polars-core/src/chunked_array/ops/filter.rs
  crates/polars-core/src/chunked_array/ops/lambda.rs
  crates/polars-ops/src/chunked_array/list/namespace.rs
Labels: rust, fix

#49 feat: Add instrumentation to the polars functions
  Cargo.lock
  Cargo.toml
  crates/Makefile
  crates/polars-arrow/Cargo.toml
  crates/polars-compute/Cargo.toml
  crates/polars-core/Cargo.toml
  crates/polars-expr/Cargo.toml
  crates/polars-expr/src/expressions/column.rs
  crates/polars-expr/src/expressions/filter.rs
  crates/polars-expr/src/expressions/gather.rs
  crates/polars-expr/src/expressions/sort.rs
  crates/polars-expr/src/expressions/sortby.rs
  crates/polars-io/Cargo.toml
  crates/polars-lazy/Cargo.toml
  crates/polars-mem-engine/Cargo.toml
  crates/polars-mem-engine/src/executors/cache.rs
  crates/polars-mem-engine/src/executors/executor.rs
  crates/polars-mem-engine/src/executors/ext_context.rs
  crates/polars-mem-engine/src/executors/filter.rs
  crates/polars-mem-engine/src/executors/group_by.rs
  crates/polars-mem-engine/src/executors/group_by_dynamic.rs
  crates/polars-mem-engine/src/executors/group_by_partitioned.rs
  crates/polars-mem-engine/src/executors/group_by_rolling.rs
  crates/polars-mem-engine/src/executors/hconcat.rs
  crates/polars-mem-engine/src/executors/projection.rs
  crates/polars-mem-engine/src/executors/projection_simple.rs
  crates/polars-mem-engine/src/executors/scan/csv.rs
  crates/polars-mem-engine/src/executors/scan/ipc.rs
  crates/polars-mem-engine/src/executors/scan/mod.rs
  crates/polars-mem-engine/src/executors/scan/parquet.rs
  crates/polars-mem-engine/src/executors/slice.rs
  crates/polars-mem-engine/src/executors/sort.rs
  crates/polars-mem-engine/src/executors/stack.rs
  crates/polars-mem-engine/src/executors/udf.rs
  crates/polars-mem-engine/src/executors/union.rs
  crates/polars-mem-engine/src/executors/unique.rs
  crates/polars-ops/Cargo.toml
  crates/polars-parquet/Cargo.toml
  crates/polars-plan/Cargo.toml
  crates/polars-plan/src/dsl/function_expr/strings.rs
  crates/polars-stream/Cargo.toml
  crates/polars-time/Cargo.toml
  crates/polars/Cargo.toml
Labels: enhancement, rust, python

#51 feat: Cast lambda expression
  crates/polars-arrow/src/compute/cast/binary_to.rs
  crates/polars-arrow/src/compute/cast/binview_to.rs
  crates/polars-arrow/src/compute/cast/mod.rs
  crates/polars-arrow/src/compute/cast/primitive_to.rs
  crates/polars-core/src/chunked_array/ops/lambda.rs
  crates/polars-core/src/chunked_array/ops/transform.rs
  crates/polars-core/src/datatypes/any_value.rs
  crates/polars-core/src/series/series_trait.rs
  crates/polars-ops/src/chunked_array/list/namespace.rs
  crates/polars-plan/src/dsl/function_expr/list.rs
Labels: enhancement, rust, python

#52 fix(rust): Reminder with negative numbers for signed numbers when rhs is scalar
  crates/polars-compute/src/arithmetic/signed.rs
Labels: rust, fix

#54 fix(rust): Add support for binary blob in lambda
  crates/polars-core/src/chunked_array/ops/filter.rs
Labels: rust, fix

#53 feat: New lambda implementation
  crates/polars-arrow/src/compute/cast/mod.rs
  crates/polars-arrow/src/compute/cast/primitive_to.rs
  crates/polars-core/src/chunked_array/ops/filter.rs
  crates/polars-core/src/chunked_array/ops/flarion_funcs.rs
  crates/polars-core/src/chunked_array/ops/lambda.rs
  crates/polars-core/src/chunked_array/ops/mod.rs
  crates/polars-core/src/chunked_array/ops/sort/mod.rs
  crates/polars-core/src/chunked_array/ops/split.rs
  crates/polars-core/src/chunked_array/ops/transform.rs
  crates/polars-core/src/series/implementations/binary.rs
  crates/polars-core/src/series/implementations/boolean.rs
  crates/polars-core/src/series/implementations/floats.rs
  crates/polars-core/src/series/implementations/list.rs
  crates/polars-core/src/series/implementations/mod.rs
  crates/polars-core/src/series/implementations/string.rs
  crates/polars-core/src/series/series_trait.rs
  crates/polars-ops/src/chunked_array/list/namespace.rs
  crates/polars-ops/src/chunked_array/strings/flarion_instr.rs
  crates/polars-ops/src/chunked_array/strings/flarion_slice.rs
  crates/polars-ops/src/chunked_array/strings/flarion_split.rs
  crates/polars-ops/src/chunked_array/strings/mod.rs
  crates/polars-ops/src/chunked_array/strings/namespace.rs
  crates/polars-ops/src/chunked_array/strings/split.rs
Labels: enhancement, rust, python

#55 feat: Contains function variant that accept Regex struct
  crates/polars-core/src/frame/group_by/into_groups.rs
  crates/polars-core/src/frame/group_by/mod.rs
  crates/polars-core/src/frame/mod.rs
  crates/polars-core/src/utils/mod.rs
  crates/polars-expr/src/expressions/aggregation.rs
  crates/polars-expr/src/expressions/apply.rs
  crates/polars-expr/src/expressions/binary.rs
  crates/polars-expr/src/expressions/flarion/normalize_nan_and_zero.rs
  crates/polars-expr/src/expressions/gather.rs
  crates/polars-expr/src/expressions/slice.rs
  crates/polars-expr/src/expressions/sort.rs
  crates/polars-expr/src/expressions/sortby.rs
  crates/polars-expr/src/expressions/window.rs
  crates/polars-mem-engine/src/executors/group_by.rs
  crates/polars-ops/src/chunked_array/strings/namespace.rs
  crates/polars-plan/src/dsl/function_expr/strings.rs
  crates/polars-plan/src/dsl/string.rs
Labels: enhancement, rust, python

#56 feat: Optimize out index series when indices are not used
  Cargo.toml
  crates/polars-arrow/src/array/primitive/mutable.rs
  crates/polars-core/src/chunked_array/ops/lambda.rs
  crates/polars-expr/src/expressions/aggregation.rs
  crates/polars-expr/src/expressions/apply.rs
  crates/polars-expr/src/expressions/column.rs
  crates/polars-expr/src/expressions/count.rs
  crates/polars-expr/src/expressions/filter.rs
  crates/polars-expr/src/expressions/flarion/normalize_nan_and_zero.rs
  crates/polars-expr/src/expressions/gather.rs
  crates/polars-expr/src/expressions/literal.rs
  crates/polars-expr/src/expressions/rolling.rs
  crates/polars-expr/src/expressions/slice.rs
  crates/polars-expr/src/expressions/sort.rs
  crates/polars-expr/src/expressions/sortby.rs
  crates/polars-expr/src/expressions/window.rs
  crates/polars-ops/src/chunked_array/list/namespace.rs
  crates/polars-plan/src/dsl/arithmetic.rs
  crates/polars-plan/src/dsl/binary.rs
  crates/polars-plan/src/dsl/expr_dyn_fn.rs
  crates/polars-plan/src/dsl/function_expr/list.rs
  crates/polars-plan/src/dsl/list.rs
  crates/polars-plan/src/dsl/mod.rs
  crates/polars-plan/src/dsl/name.rs
  crates/polars-plan/src/dsl/struct_.rs
  crates/polars-sql/tests/functions_cumulative.rs
Labels: enhancement, rust, python

#57 feat: More regex optimizations
  crates/polars-core/src/utils/mod.rs
  crates/polars-ops/src/chunked_array/strings/extract.rs
  crates/polars-ops/src/chunked_array/strings/namespace.rs
  crates/polars-plan/src/dsl/function_expr/strings.rs
  crates/polars-plan/src/dsl/string.rs
Labels: enhancement, rust, python

#58 fix: IpcStreamBatchedWriter should not require Seek by default
  crates/polars-io/src/ipc/ipc_stream.rs
Labels: rust, python, fix

#59 feat: Don't return an owned string in substring functions
  crates/polars-core/src/chunked_array/ops/flarion_funcs.rs
  crates/polars-core/src/chunked_array/ops/lambda.rs
  crates/polars-io/src/ipc/ipc_stream.rs
Labels: enhancement, rust, python

#60 feat: Add function finish_with_stream_position to the IpcStreamWriter
  crates/polars-io/src/ipc/ipc_stream.rs
Labels: enhancement, rust, python
